server:
  port: 8080
  servlet:
    context-path: "/mybatisplus"  # 请求前缀

#mysql
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
#    driver-class-name: com.mysql.jdbc.Driver

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:com/xiaofeng/mybatisplus/mapper/xml/*.xml
  type-aliases-package: com.xiaofeng.mybatisplus.entity
#  configuration:
#    map-underscore-to-camel-case: true  # 下划线与驼峰互转


logging:
  config: classpath:log4j2.yml
